### ISSUE TITLE
Installer compatibility

### ISSUE THREAD

**Issue by TanninOne** [Nexus-Mods/Vortex#598]
This issue is used to track issues related to incompatible installers

ENBs (probably related)
- [x] ReShade with ENB #369
- [x] Caffeine ENB #421
- [x] Mythical VR ENB #440
- [x] 1982 ENB #511
- [x] VR ENB #593
- [x] IAXE ENB #597
- [x] Graphic Enhancement Mod #543

Others
- [x] Weapon Animations Replacer #375
- [x] Simply Stronger Dragons #569
- [X] Legacy of the Dragonborn #609
- [x] 4. Texture Addon - All DLCs #704
- [x] SKSC Scripts #776
- [x] Pelted Chairs #731
